#Install Apache & PHP
FROM php:8.0.13-apache

WORKDIR /src

ENV PORT 80

#Install libraries for PHP
RUN apt-get update && apt-get install -y libxml2-dev libpq-dev && docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN docker-php-ext-install mysqli pdo_mysql pdo_pgsql pgsql session soap

#Config PHP
COPY conf/php.ini /usr/local/etc/php/php.ini

#Config Apache
COPY conf/vhost.conf /etc/apache2/sites-available/000-default.conf
COPY conf/apache.conf /etc/apache2/conf-available/z-src.conf
RUN a2enmod rewrite remoteip && \
	chown -R www-data /src

#Rights on the env
RUN sed -ri 's/^www-data:x:33:33:/www-data:x:1000:50:/' /etc/passwd

CMD sed -i "s/80/$PORT/g" /etc/apache2/sites-enabled/000-default.conf /etc/apache2/ports.conf && docker-php-entrypoint apache2-foreground